apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-auth-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: aws-auth-operator-controller-manager
  namespace: aws-auth-operator-system