# permissions for end users to edit eksauthmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eksauthmap-editor-role
rules:
- apiGroups:
  - eksauth.operators.com
  resources:
  - eksauthmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eksauth.operators.com
  resources:
  - eksauthmaps/status
  verbs:
  - get
